version: "3.9"

services:
  angular:
    container_name: notes-ng
    image: ${APP_NAME}:ng
    build:
      dockerfile_inline: |
        FROM ${BUILT_IMAGE}
        WORKDIR /${APP_NAME}
        COPY . .
        RUN bun i
        CMD ["ng", "serve", "--host", "0.0.0.0"]
    ports:
      - "4200:4200"
    environment:
      - APP_NAME
      - BUILT_IMAGE
    volumes:
      - .:/${APP_NAME}
    depends_on:
      - springboot
  
  springboot:
    container_name: notes-springboot
    image: ${APP_NAME}:springboot
    build:
      dockerfile_inline: |
        FROM eclipse-temurin:21-alpine
        WORKDIR /api
        COPY ./api .
        RUN chmod 777 ./gradlew
        CMD ["./gradlew", "run"]
    ports:
      - "9090:9090"
    environment:
      - APP_NAME
      - BUILT_IMAGE
    volumes:
      - ./api:/api
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13.14-alpine3.19
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 618789
      POSTGRES_DB: notes
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: 618789
    depends_on:
      - postgres
    ports:
      - "54621:80"
      - "443:443"
